<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NovaGlass</AssemblyName>
    <RootNamespace>NovaGlass</RootNamespace>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>
  <ItemGroup>
    <None Update="www\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Scripts\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
